//IEC Addressen
#define	RSURE3				8
#define	PM2813				28



// GPIB Device
#define GPIB_TSU				"GPIB::1"
#define GPIB_CMD60				"GPIB::5"   //[@GC 21.07.11] 
#define GPIB_NRVS				"GPIB::15"	//[@GC 21.07.11] 
#define GPIB_HP8595A			"GPIB::9"	//[@GC 21.07.11] 
#define GPIB_HP8594E			"GPIB::17"	//[@GC 27.07.11] 

// TSU Relais-Boards
#define REL1				6   //mbi-addr
#define	REL2				5   //mbi-addr
// TSU internal A/B/C - Bus
#define	A					1   
#define	B					2   
#define	C					3   
#define	A1					4   
#define	A2					7   
#define	B1					5   
#define	B2					8   
#define	C1					6   
#define	C2					9   
#define B2_SENSE			1
#define	A1_SENSE			2   
#define	A2_SENSE			3
#define	C1_SENSE			3
#define	C2_SENSE			4
#define NOT_CONNECT			0



// CMD60 defines:

#define	NONE				0   

#define EUROPE				1
#define CHINESE 			2
#define SOUTH_AMERICAN		3
#define	RF_ATTENUATION_FINAL		-40.0	  //RF-IN/OUT Attenuation-->used to get more power
#define	RF_ATTENUATION_FUNCTION		-20.0


